# B0003

As commands are executed asynchronously, it is possible to issue a command on an entity that will no longer exist at the time of the command execution.

Erroneous code example:

```rust,should_panic
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .add_systems(Update, despawning)
        .add_systems(Update, use_entity.after(despawning))
        .run();
}

#[derive(Resource)]
struct MyEntity(Entity);

#[derive(Component)]
struct Hello;

fn setup(mut commands: Commands) {
    let entity = commands.spawn_empty().id();
    commands.insert_resource(MyEntity(entity));
}

fn despawning(mut commands: Commands, my_entity: Res<MyEntity>) {
    commands.entity(my_entity.0).despawn();
}

fn use_entity(mut commands: Commands, my_entity: Res<MyEntity>) {
    commands.entity(my_entity.0).insert(Hello);
}
```

This will panic, as system `use_entity` is executed after system `despawning`. Without the system ordering specified here, the ordering would be random and this code would panic half the time.

The panic message is telling you that the entity (`1v0`) doesn't exist and the command that failed (creating EntityCommands):

```text
thread '<unnamed>' panicked at examples/use_entity_after_despawn.rs:28:14:
Attempting to create an EntityCommands for entity 1v0, which doesn't exist.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `use_entity_after_despawn::use_entity`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

The panic message also tells us in which system the panic happens.

Additionally, you can enable the `trace` feature of Bevy. This will add a panic handler that will print more information:

```text
   0: bevy_ecs::system::function_system::system
           with name="use_entity_after_despawn::use_entity"
             at crates/bevy_ecs/src/system/function_system.rs:47
thread '<unnamed>' panicked at examples/use_entity_after_despawn.rs:28:14:
Attempting to create an EntityCommands for entity 1v0, which doesn't exist.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `use_entity_after_despawn::use_entity`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

To get the system that created the despawn command, you can enable DEBUG logs for crate `bevy_ecs`, you can do this by setting the environment variable `RUST_LOG=bevy_ecs=debug`. This will log:

```text
2023-12-21T12:05:27.566516Z DEBUG system_commands{name="use_entity_after_despawn::despawning"}: bevy_ecs::world::entity_ref: Despawning entity 1v0
   0: bevy_ecs::system::function_system::system
           with name="use_entity_after_despawn::use_entity"
             at crates/bevy_ecs/src/system/function_system.rs:47
thread '<unnamed>' panicked at examples/use_entity_after_despawn.rs:28:14:
Attempting to create an EntityCommands for entity 1v0, which doesn't exist.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `use_entity_after_despawn::use_entity`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

From the first line, you know the entity `1v0` was despawned when executing a command from system `despawning`. In a real case, you could have many log lines, you will need to search for the exact entity from the panic message.

Combining those two, you should get enough information to understand why this panic is happening and how to fix it.